---
- name: Create 'students' group
  group:
    name: students
    state: present

- name: Create 'geocompr_student'
  user:
    name: geocompr_student
    shell: /bin/bash
    password: "{{ 'geocompx' | password_hash('sha512') }}"

- name: Assign 'geocompr_student' to students
  user:
    name: geocompr_student
    groups: students
    append: yes

- name: Create a directory for students
  file:
    path: /opt/data
    state: directory
    mode: 0750
    group: students
